version: 2.1
executors:
  default:
    docker:
      - image: circleci/python:3.9

jobs:
  build:
    executor: default
    steps:
      - checkout

      # Install Nginx
      - run:
          name: Install Nginx
          command: |
            sudo apt-get update
            sudo apt-get install -y nginx
      #Checking Docker Version and Enabling it
      - run:
          name: Installation of Docker
          command: |
            sudo apt update
            sudo apt-get install apt-utils
            docker version
      #Enabling Docker
    # { - run:
          name: Enabling Docker
          command: |
            sudo service docker start
            sudo service docker enable
            docker version}
            
      # Build Nginx Docker Image
      - run:
          name: Build Nginx Docker Image
          command: |
            docker build -t sample -f src/Dockerfile .
            docker login -u sheikaslam -p A$lam2121@
            docker push sheikaslam/circleci:tagname
            
      # Start Nginx
      - run:
          name: Start Nginx
          command: sudo service nginx start

workflows:
  version: 2
  build:
    jobs:
      - build
