version: 2.1
executors:
  default:
    docker:
      - image: nginx:latest

jobs:
  build:
    executor: default
    steps:
      - checkout

      - run:
          name: Build Nginx Docker Image
          command: |
            docker build -t your-dockerhub-username/nginx-app:${CIRCLE_SHA1} .
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push your-dockerhub-username/nginx-app:${CIRCLE_SHA1}

workflows:
  version: 2
  build:
    jobs:
      - build
