---
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout

      # Install Nginx
      - run:
          name: Install Nginx
          command: |
            sudo apt-get update
            sudo apt-get install -y nginx

      # Start Nginx
      - run:
          name: Start Nginx
          command: sudo service nginx start
