on:
  push:
    branches:
      - main

 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
           npm config set registry ${{ secrets.REGISTRY_URL }}
           npm config set registry ${{ secrets.SEMVER_URL }}
           npm install

      - name: Build front-end code
        run: npm run build

      - name: Deploy to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage container create --name avanpeusblobcontainer --account-name avanpeusblob --account-key mdwm1zxwnybFD32B7E/DlmVy3sE47A8YTPEE/ts8MuKPrirdiq4NNF1tjJea2uYs4lAynoH3dlK9+AStIL/gpw==
            az storage blob upload-batch --destination avanpeusblobcontainer --source ./dist --account-name avanpeusblob --account-key mdwm1zxwnybFD32B7E/DlmVy3sE47A8YTPEE/ts8MuKPrirdiq4NNF1tjJea2uYs4lAynoH3dlK9+AStIL/gpw==
