version: 2.1
executors:
  default:
    docker:
      - image: circleci/python:3.9

jobs:
  build:
    executor: default
    steps:
      - checkout

      # Install Nginx
      - run:
          name: Install Nginx
          command: |
            sudo apt-get update
            sudo apt-get install -y nginx

      # Build Nginx Docker Image
      - run:
          name: Build Nginx Docker Image
          command: |
            docker build -t your-dockerhub-username/nginx-app:${CIRCLE_SHA1} -f /.circleci/project/Dockerfile
            echo "A$lam2121@" | docker login -u "sheikaslam" --password-stdin
            docker push your-dockerhub-username/nginx-app:${CIRCLE_SHA1}

      # Start Nginx
      - run:
          name: Start Nginx
          command: sudo service nginx start

workflows:
  version: 2
  build:
    jobs:
      - build
