version: 2.1
executors:
  default:
    docker:
      - image: circleci/python:3.9

jobs:
  build:
    executor: default
    steps:
      - checkout

      # Install Nginx
      - run:
          name: Install Nginx
          command: |
            sudo apt-get update
            sudo apt-get install -y nginx
            
      # Setup Docker Environment
      - setup_remote_docker:
          version: 20.10.7

      # Build Nginx Docker Image
      - run:
          name: Build Nginx Docker Image
          command: |
            docker build -t sample -f src/Dockerfile .
            docker login -u sheikaslam --password-stdin
            docker push sheikaslam/circleci:tagname
            
      # Start Nginx
      - run:
          name: Start Nginx
          command: sudo service nginx start

workflows:
  version: 2
  build:
    jobs:
      - build
      #
