version: 2.1
executors:
  default:
    docker:
      - image: circleci/python:3.9

jobs:
  build:
    executor: default
    steps:
      - checkout

      # Install Nginx
      - run:
          name: Install Nginx
          command: |
            sudo apt-get update
            sudo apt-get install -y nginx
      #Checking Docker Version and Enabling it
      - run:
          name: Installation of Docker
          command: |
            sudo apt update
            sudo apt-get install apt-utils
            sudo apt install apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
            echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt install docker-ce docker-ce-cli containerd.io
            sudo apt update
            docker version
      #Enabling Docker
      - run:
          name: Enabling Docker
          command: |
            sudo service docker start
            sudo service docker enable
            docker version
            
      # Build Nginx Docker Image
      - run:
          name: Build Nginx Docker Image
          command: |
            docker build -t sample -f src/Dockerfile .
            docker login -u sheikaslam -p A$lam2121@
            docker push sheikaslam/circleci:tagname
            
      # Start Nginx
      - run:
          name: Start Nginx
          command: sudo service nginx start

workflows:
  version: 2
  build:
    jobs:
      - build
